ERROR - 2023-07-19 08:08:26 --> mysqli_sql_exception: Unknown column 'user_name' in 'field list' in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:08:26 --> Unknown column 'user_name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')')
 4 APPPATH\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:08:50 --> mysqli_sql_exception: Unknown column 'user_name' in 'field list' in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:08:50 --> Unknown column 'user_name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')')
 4 APPPATH\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:08 AM\', \'djhskhvfbnj\', \'0\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:09:52 --> mysqli_sql_exception: Unknown column 'user_name' in 'field list' in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:09:52 --> Unknown column 'user_name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:09 AM\', \'djhskhvfbnj\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:09 AM\', \'djhskhvfbnj\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:09 AM\', \'djhskhvfbnj\', \'0\')')
 4 APPPATH\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:09 AM\', \'djhskhvfbnj\', \'0\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:10:16 --> mysqli_sql_exception: Unknown column 'user_name' in 'field list' in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:10:16 --> Unknown column 'user_name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:10 AM\', \'djhskhvfbnj\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:10 AM\', \'djhskhvfbnj\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:10 AM\', \'djhskhvfbnj\', \'0\')')
 4 APPPATH\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:10 AM\', \'djhskhvfbnj\', \'0\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:11:06 --> mysqli_sql_exception: Unknown column 'user_name' in 'field list' in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:11:06 --> Unknown column 'user_name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:11 AM\', \'djhskhvfbnj\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:11 AM\', \'djhskhvfbnj\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:11 AM\', \'djhskhvfbnj\', \'0\')')
 4 APPPATH\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:11 AM\', \'djhskhvfbnj\', \'0\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:12:47 --> mysqli_sql_exception: Unknown column 'user_name' in 'field list' in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:12:47 --> Unknown column 'user_name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:12 AM\', \'djhskhvfbnj\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:12 AM\', \'djhskhvfbnj\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:12 AM\', \'djhskhvfbnj\', \'0\')')
 4 APPPATH\Models\PostModel.php(97): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `user_name`, `dp_url`, `timestamp`, `keywords`, `published`)
         VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\', \'anshul\', \'fd\', \'07/19/2023 08:12 AM\', \'djhskhvfbnj\', \'0\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:13:46 --> mysqli_sql_exception: Column count doesn't match value count at row 1 in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(94): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:13:46 --> Column count doesn't match value count at row 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:13 AM\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:13 AM\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:13 AM\')')
 4 APPPATH\Models\PostModel.php(94): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:13 AM\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:14:13 --> mysqli_sql_exception: Column count doesn't match value count at row 1 in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(94): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:14:13 --> Column count doesn't match value count at row 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:14 AM\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:14 AM\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:14 AM\')')
 4 APPPATH\Models\PostModel.php(94): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'djhskhvfbnj\', \'0\',\'0707/1919/2023 08:14 AM\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
ERROR - 2023-07-19 08:15:40 --> mysqli_sql_exception: Column count doesn't match value count at row 1 in C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg...', 0)
#1 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg...')
#2 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg...')
#3 C:\xampp\htdocs\myfirst\app\Models\PostModel.php(94): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg...')
#4 C:\xampp\htdocs\myfirst\app\Controllers\Users.php(54): App\Models\PostModel->save(Array)
#5 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\Users->store()
#6 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\myfirst\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\myfirst\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-19 08:15:40 --> Column count doesn't match value count at row 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'0707/1919/2023 08:15 AM\',\'djhskhvfbnj\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'0707/1919/2023 08:15 AM\',\'djhskhvfbnj\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'0707/1919/2023 08:15 AM\',\'djhskhvfbnj\', \'0\')')
 4 APPPATH\Models\PostModel.php(94): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sg_posts` (`post_id`, `post_title`, `post_description`, `cover_image_url`, `liked`, `created_by`, `timestamp`, `keywords`, `published`,`date`) VALUES (NULL, \'test\', \'test\', \'vnbchdgbvhjs\', \'0\', \'1\',\'0707/1919/2023 08:15 AM\',\'djhskhvfbnj\', \'0\')')
 5 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:17:07 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert_id()
in APPPATH\Models\PostModel.php on line 94.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:17:16 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert_id()
in APPPATH\Models\PostModel.php on line 94.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:20:13 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert_id()
in APPPATH\Models\PostModel.php on line 94.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:22:03 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::mysqli_insert_id()
in APPPATH\Models\PostModel.php on line 95.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:23:22 --> mysqli_insert_id(): Argument #1 ($mysql) must be of type mysqli, CodeIgniter\Database\MySQLi\Connection given
in APPPATH\Models\PostModel.php on line 95.
 1 APPPATH\Models\PostModel.php(95): mysqli_insert_id(Object(CodeIgniter\Database\MySQLi\Connection))
 2 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 3 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 4 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:34:20 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 58.
 1 APPPATH\Controllers\Users.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 58)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:35:00 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 58.
 1 APPPATH\Controllers\Users.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 58)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:36:44 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 59.
 1 APPPATH\Controllers\Users.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:38:06 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 59.
 1 APPPATH\Controllers\Users.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:38:24 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert_id()
in APPPATH\Models\PostModel.php on line 94.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:38:39 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 59.
 1 APPPATH\Controllers\Users.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:39:03 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 59.
 1 APPPATH\Controllers\Users.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:39:53 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 59.
 1 APPPATH\Controllers\Users.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:41:02 --> Call to undefined method App\Models\PostModel::last
in SYSTEMPATH\Model.php on line 848.
 1 APPPATH\Controllers\Users.php(57): CodeIgniter\Model->__call('last', [])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:42:01 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 59.
 1 APPPATH\Controllers\Users.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 08:42:21 --> Undefined array key "pots_id"
in APPPATH\Controllers\Users.php on line 59.
 1 APPPATH\Controllers\Users.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pots_id"', 'C:\\xampp\\htdocs\\myfirst\\app\\Controllers\\Users.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 09:11:47 --> Object of class DateTime could not be converted to string
in APPPATH\Models\PostModel.php on line 96.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 09:12:03 --> Object of class DateTime could not be converted to string
in APPPATH\Models\PostModel.php on line 96.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 09:12:29 --> Object of class DateTime could not be converted to string
in APPPATH\Models\PostModel.php on line 90.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 14:44:51 --> Object of class DateTime could not be converted to string
in APPPATH\Models\PostModel.php on line 98.
 1 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
CRITICAL - 2023-07-19 09:15:14 --> DateTime::format() expects exactly 1 argument, 2 given
in APPPATH\Models\PostModel.php on line 92.
 1 APPPATH\Models\PostModel.php(92): DateTime->format('Y-m-d H:i A', 1689758114)
 2 APPPATH\Controllers\Users.php(54): App\Models\PostModel->save([...])
 3 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Users->store()
 4 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\myfirst\\public\\index.php')
